name: Daily Repository Backup
on:
    schedule:
        - cron: "0 2 * * *" # Run daily at 2 AM UTC
    workflow_dispatch: # Allow manual triggering

jobs:
    backup:
        name: Backup Repositories
        runs-on: ubuntu-latest
        steps:
            - name: Checkout backup repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.BACKUP_TOKEN }}
                  fetch-depth: 0

            - name: Setup Git user
              run: |
                  git config --global user.name "Backup Bot"
                  git config --global user.email "ethank2222@gmail.com"

            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.21"

            - name: Validate environment
              env:
                  BACKUP_TOKEN: ${{ secrets.BACKUP_TOKEN }}
                  GITHUB_REPOSITORY: ${{ github.repository }}
              run: |
                  if [ -z "$BACKUP_TOKEN" ]; then
                    echo "❌ Error: BACKUP_TOKEN not set"
                    exit 1
                  fi
                  if [ ! -f repositories.txt ]; then
                    echo "❌ Error: repositories.txt not found"
                    exit 1
                  fi
                  echo "✅ Environment validated"

            - name: Run backup script
              id: backup
              env:
                  BACKUP_TOKEN: ${{ secrets.BACKUP_TOKEN }}
                  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
                  GITHUB_SERVER_URL: ${{ github.server_url }}
                  GITHUB_REPOSITORY: ${{ github.repository }}
                  GITHUB_RUN_ID: ${{ github.run_id }}
              run: |
                  echo "🚀 Starting backup process..."
                  if ! go run backup.go; then
                    echo "❌ Backup script failed"
                    exit 1
                  fi
                  echo "✅ Backup script completed successfully"

            - name: Check for changes
              id: changes
              run: |
                  if git diff --quiet; then
                    echo "no_changes=true" >> $GITHUB_OUTPUT
                    echo "ℹ️  No changes to commit"
                  else
                    echo "no_changes=false" >> $GITHUB_OUTPUT
                    echo "ℹ️  Changes detected"
                  fi

            - name: Commit and push changes
              if: steps.changes.outputs.no_changes != 'true'
              run: |
                  git add .
                  git commit -m "Daily mirror backup - $(date +%Y-%m-%d)"
                  git push origin main
                  echo "✅ Changes committed and pushed"

    cleanup:
        name: Cleanup
        runs-on: ubuntu-latest
        needs: backup
        if: always()
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.21"

            - name: Run cleanup checks
              env:
                  GITHUB_REPOSITORY: ${{ github.repository }}
              run: |
                  echo "ℹ️  Running cleanup checks..."
                  if [ -f backup-results.json ]; then
                    echo "ℹ️  Found backup results file"
                  fi
                  if [ -d backups ]; then
                    echo "ℹ️  Backup directory exists"
                    zip_count=$(find backups -name "*.zip" 2>/dev/null | wc -l)
                    echo "  - ZIP files: $zip_count"
                  else
                    echo "⚠️  No backup directory found"
                  fi
                  echo "✅ Cleanup checks completed"
