name: Daily Repository Backup
on:
    schedule:
        - cron: "0 2 * * *" # Run daily at 2 AM UTC
    workflow_dispatch: # Allow manual triggering

jobs:
    backup:
        name: Backup Repositories
        runs-on: ubuntu-latest
        steps:
            - name: Checkout backup repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.BACKUP_TOKEN }}
                  fetch-depth: 0

            - name: Setup Git user
              run: |
                  git config --global user.name "Backup Bot"
                  git config --global user.email "ethank2222@gmail.com"

            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.21"

            - name: Install dependencies
              run: go mod download

            - name: Make utility script executable
              run: chmod +x scripts/backup-utils.sh

            - name: Validate environment variables
              run: ./scripts/backup-utils.sh validate

            - name: Run backup script
              id: backup
              env:
                  BACKUP_TOKEN: ${{ secrets.BACKUP_TOKEN }}
                  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
                  GITHUB_SERVER_URL: ${{ github.server_url }}
                  GITHUB_REPOSITORY: ${{ github.repository }}
                  GITHUB_RUN_ID: ${{ github.run_id }}
              run: |
                  echo "🚀 Starting backup process..."
                  if ! go run backup.go; then
                    echo "❌ Backup script failed"
                    exit 1
                  fi
                  echo "✅ Backup script completed successfully"

            - name: Commit and push backups
              id: commit
              run: ./scripts/backup-utils.sh commit-push

            - name: Send final notification
              if: always()
              env:
                  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
                  GITHUB_SERVER_URL: ${{ github.server_url }}
                  GITHUB_REPOSITORY: ${{ github.repository }}
                  GITHUB_RUN_ID: ${{ github.run_id }}
              run: ./scripts/backup-utils.sh send-notification "${{ job.status }}"

    cleanup:
        name: Cleanup
        runs-on: ubuntu-latest
        needs: backup
        if: always()
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.21"

            - name: Run cleanup checks
              run: ./scripts/backup-utils.sh cleanup
